version: "3.3"

services:
  app:
    image: registry.slowcoder.com/mlabouardy/oneshot-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker